sudo: required
services:
    - docker

before_install:
    - docker build -t herbertbintoroe/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true herbertbintoroe/react-test npm test

after_success:
    - docker build -t herbertbintoroe/multi-client ./client
    - docker build -t herbertbintoroe/multi-nginx ./nginx
    - docker build -t herbertbintoroe/multi-server ./server
    - docker build -t herbertbintoroe/multi-worker ./worker

    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take those images and push them to docker-hub
    - docker push herbertbintoroe/multi-client
    - docker push herbertbintoroe/multi-nginx
    - docker push herbertbintoroe/multi-server
    - docker push herbertbintoroe/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-485801149432
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY