version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment: 
            - POSTGRES_PASSWORD=mypassword
    redis:
        image: 'redis:latest'
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        depends_on: 
            - api
            - client
        ports:
            - '3050:80'
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            # Don't do anything to this folder
            - /app/node_modules
            # Copy everything inside app to the server folder (Except for node modules)
            - ./server:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379 # Default configuration from redis image
            - PGUSER=postgres
            - PGHOST=postgres 
            - PGDATABASE=postgres
            - PGPASSWORD=mypassword
            - PGPORT=5432
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
        stdin_open: true
    worker:
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
            - ./worker:/app